export const Layout = {
    columnWidth: 350,
    rowHeight: 175,
    subjectHeight: 115,
    subjectWidth: 200,
    paddingHorizontal: 120,
    paddingVertical: 120,
    subjectPadding: 16,
    semesterTitleInset: 250,
    sidebarWidth: 240,
    semesterColumnBottomPadding: 50,
    edgeXOffsetStep: 12,
    detailMenuSubjectHeight: 140,
    detailMenuSubjectWidth: 250,
    detailMenuSubjectPadding: 16,
};